version: '3.8'

services:
  raspy-hermes:
    build: .
    container_name: raspy_hermes_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./skills:/app/skills
